### ISSUE TITLE
Document that it's pre-compiled on npm/yarn

### ISSUE THREAD

**Issue by tandrewnichols** [JanPeter/neo4js#6]
Rather than making _every potential user_ setup and use babel to use this, couldn't you just run babel as a pre publish step (or something manual even), so that it's more user friendly? I mean, I like babel and all, but I don't want to _have_ to use babel to compile someone else's project, especially as my target environment for this is node where preprocessing js is sort of a weird thing people don't really do much of. Ideally, I would just `npm install` and then `require`, and it would just work. I'm only opening this issue because I'm not especially satisfied with the state of neo4j wrappers in the javascript world, and this one looks promising, but if I have to jump through hoops to use it, the answer is going to be "no."

**Comment by tandrewnichols** [comment]
Ah, I just discovered (by `npm install`ing on a whim) that you have actually done this. I amend my issue to be "Please document that you can just `require` this in node." It wasn't clear to me from the README that the npm/yarn version of this _is compiled_. And I think that matters a lot. Like I said before, I wasn't willing to use this if I had to jump through hoops.

**Comment by JanPeter** [comment]
Hi, first of all thanks for showing interest in my library and giving me feeback!
I'm quite new to open source and publishing a library, so this is actually not an easy topic for me. The docs aren't nowhere complete yet, it's quite hard for me to think about all the different approaches and setups. I'll try to add this to the documentation starting with next week!

But I would be more than happy if you would create a pull request for the docs ;)

**Comment by tandrewnichols** [comment]
Yeah, there's no doubt that the javascript community is extremely fragmented. I think you can probably assume there's 3 major audiences for something like this: node.js, client-side via babel + some sort of build tool (gulp, grunt, webpack, etc.), and more traditional client-side usage via `<script>` and `window.thing`. But I don't think you need to go into too much detail about various setups. The thing I think is worth pointing out is that the version of this library you get when you `yarn add` or `npm install` is the not the version you see on Github (e.g. there's no "src" directory, and instead there's a "lib" with compiled code).

**Comment by JanPeter** [comment]
But I think neo4-js just makes sense for the forst audience. I mean it should be possible, theoretically, to run neo4-js in your client app directly in the browser of the user, but as you need to provide the bolt_uri, bolt_port, neo4j-user and the neo4j-password everybody could connect to your database, which is probably not what you want.

I thought about 3 different audiences:
People who are writing their backend in plain javascript; people who are coding with babel; and people who are coding with babel and flow; potentially there might also be a typescript user.

**Comment by JanPeter** [comment]
I added a part in the [README](https://github.com/JanPeter/neo4js#installing-it-for-vanilla-nodejs-without-babel) for this here. Hope this helps!
