### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by tandrewnichols** [JanPeter/neo4js#7]
Getting this when trying to require neo4js. Accoding to [this](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined), you need to compile async/await code with `babel-polyfill`.

**Comment by tandrewnichols** [comment]
Hmm, your package.json include `babel-polyfill`. I should start checking these things before I open issues. Maybe something is wrong in your babelrc (maybe you need `es2017` for example)?

**Comment by tandrewnichols** [comment]
I'm using node 7.10.1, fwiw.

**Comment by tandrewnichols** [comment]
[This](https://babeljs.io/docs/usage/polyfill/) suggests maybe the problem is that `babel-polyfill` is listed as a dev dependency when it should be a regular dependency. _Maybe_ . . . I don't know that much about these things.

**Comment by JanPeter** [comment]
I'm currently developing a project myself using neo4-js and I also noticed that I need to add babel-polyfill as an dependency and I need to require the polyfill with `import "babel-polyfill";` for my project. I'm not happy with this! So I'm able to replicate the problem. I try to fix this in the coming days!

Thanks for your feedback! That means a lot to me! I hope you keep trying my library 👍

**Comment by tandrewnichols** [comment]
Yeah, actually, I installed `babel-polyfill` and required it prior to requiring this and everything worked fine, so I assume importing it somewhere here would be sufficient.

**Comment by JanPeter** [comment]
I asked one of the core contributors of babel, he said either import the babel-polyfill within the server application or do a runtime transformation. I'll give the later a try this week!
