### ISSUE TITLE
Make decorator stuff easier to consume in non-decorator environments

### ISSUE THREAD

**Issue by tandrewnichols** [JanPeter/neo4js#9]
Possibly by renaming some concepts (`connect`) and tweaking how relationships are created. See #8.

**Comment by JanPeter** [comment]
Finally I think I've found a good compromise. I completely reworked the way to define a new relation. It makes much more sense now. I'm actually working on a "compiler" to transform this code into a schema:

```
type User {
  firstname: String,
  lastname: String,
  tasks: has many Task using TaskCreatorRelation
}

type Task {
  title: String,
  done: Boolean,
  creator: has one User using TaskCreatorRelation
}

relation TaskCreatorRelation from User to Task via "created" { }
```

And while writing this compiler, I realised that the current way of defining relations is pretty hard to reason about.

So now you create a new relation and declare the direction with it (for recursive relations there is another way to define the direction)
```
const UserTaskRelation = relation
  .from(() => User)
  .to(Task)
  .via("created");
```
Which translates into, create a relation from User to Task and use the "created" label to describe the relation in the neo4j database. If you looked closely you can lazy initialise the Model definitions for the relation. If you don't use the arrow syntax, you'll need to declare the model before you're able to create the relation. With the arrow syntax, it doesn't matter when you declare your model. Lazy initialisation is now usable on each decorator or it's non-decorator solution for the models and relations.

To use this relation I'm going to reference the `UserTaskRelation` within my ModelInstance definition like the following:
```
@model(() => User)
class UserInstance extends ModelInstance<UserProps> {
  @hasMany(() => Task, () => UserTaskRelation)
  createdTasks;
}
```

With this definition I'm able to reason pretty fast about the relation when I have a look at the instance. Before this change, I needed to go to the relation declaration to know if it is a 1:n or n:m or n:1 relationship.

Let's have a look at how you are able to create the same model as above without decorators:

```
const UserTaskRelation = relation
  .from(() => User)
  .to(Task)
  .via("created");

const User = new Model("User");
class UserInstance extends ModelInstance { }
UserInstance = extendModelInstance(UserInstance);
UserInstance.hasMany("createdTasks", () => Task, UserTaskRelation);
UserInstance.model(User);
```

I added a new function `extendModelInstance` to add the `hasMany`, `hasOne`, `defaultProps` and `model` functions. The syntax for those methods is the same as for the decorators, with the only difference in the `hasMany` and `hasOne` functions. For those two functions the first parameter is the property name you'll get your functions added onto your instance and the rest of the parameters after the property name is the same as for the decorators. With the current implementation you need to call the `model` function after all others. I might change that in future, but as long as the decorator proposal is not stable I'll wait for that.

Hope this helps! Let me know what you think about that.

**Comment by tandrewnichols** [comment]
I like this _much_ more:

```
const UserTaskRelation = relation
  .from(() => User)
  .to(Task)
  .via("created");
```

Very easy to grok.

I don't fully understand the reason for `extendModelInstance`. If it's adding functions, couldn't you just make those static functions on the ModelInstance class? Like:

```
class ModelInstance {
  static hasMany(name, base, relationship) {
    // do stuff
  }
}
```

Static functions are inherited as well.

**Comment by JanPeter** [comment]
The problem with the static functions is that I need access to your newly defined class. If I created them as static functions, I'm not able to tell the model about it's ModelInstance class. So the Model will only create instances of the ModelInstance class directly. With that I'll lose all your custom functions on your ModelInstance. Hope I didn't confuse you now...

I tried this before creating this `extendModelInstance` function and ended up with a `model` function like this, without the other stuff I do in the `model` function:

```
class ModelInstance {
  ...
  static model(model) {
    model.modelInstance = ModelInstance;
  }
```

If you have an idea how I'm able to handle this let me know! I don't like the new function either ;)

**Comment by tandrewnichols** [comment]
Hmm, yeah, I see what you mean. It seems like

```
static create() {
  return new this
}
```

should work, but it doesn't. You could do something like

```
static create() {
  var Clss = this.getClass()
  return new Clss // or do whatever you need to do here
}
```

but then every model has to define it's own `getClass` that does nothing more than:

```
class Foo {
  static getClass() {
    return Foo
  }
}
```

which doesn't seem great to have to do every time.

**Comment by JanPeter** [comment]
Yep...Just curious, why are you not using babel with decorators?

**Comment by tandrewnichols** [comment]
Cause I'm working in node. I know you _can_ still do that, but I don't consider it reasonable. I only transpile code for the client. (And even when I use babel, I don't typically use stage-0 features. I think I've only ever used stage-2 and up.)

**Comment by tandrewnichols** [comment]
I just checked and I see that they are stage-2. I don't know if that was a recent change or if I just read it wrong when I previously looked at them. None the less, I still don't prefer to do transpiling on the server.

**Comment by JanPeter** [comment]
Well I'm transpiling code on the server so I can use flow and things like decorators.

It is in stage-2 currently. But thte babel plugins are not ready for stage-2 yet. I'm curious if I need to change a lot to support the new implementation...

**Comment by tandrewnichols** [comment]
I mean, everything in your examples here _except_ the decorators are features that recent versions of node support, so I think it's ok.
